version: '3.8'

services:
  master:
    build:
      context: .
    ports:
     - 8089:8089
    command: /usr/local/bin/locust -f /user/src/app/locustfile.py --master -H http://master:8089 --web-auth ${USER}:${PASSWORD}
  worker:
    build:
      context: .
    command: /usr/local/bin/locust -f /user/src/app/locustfile.py --worker --master-host master
    environment:
      - ${ENV}
      - ${LOG_LEVEL}