version: '3'
services:
    spanner:
     image: gcr.io/cloud-spanner-emulator/emulator:1.4.2
     ports:
         - "9010:9010"
         - "9020:9020"

    gcloud-spanner-init:
      image: gcr.io/google.com/cloudsdktool/cloud-sdk:388.0.0-slim
      command: >
       bash -c 'gcloud config configurations create emulator &&
               gcloud config set auth/disable_credentials true &&
               gcloud config set project $${PROJECT_ID} &&
               gcloud config set api_endpoint_overrides/spanner $${SPANNER_EMULATOR_URL} &&
               gcloud config set auth/disable_credentials true &&
               gcloud spanner instances create $${INSTANCE_NAME} --config=emulator-config --description=Emulator --nodes=1 &&
               gcloud spanner databases create $${DATABASE_NAME} --instance=$${INSTANCE_NAME}'
      environment:
        PROJECT_ID: "local"
        SPANNER_EMULATOR_URL: "http://spanner:9020/"
        INSTANCE_NAME: "local"
        DATABASE_NAME: "stress-apps"

    spanner-cli:
      image: sjdaws/spanner-cli:latest
      environment:
        SPANNER_EMULATOR_HOST: "spanner:9010"
      command: ['sh', '-c', 'echo this container keep running && tail -f /dev/null']