version: '3.8'
services:
  spanner:
    image: gcr.io/cloud-spanner-emulator/emulator:1.4.2
    ports:
      - "9010:9010"
      - "9020:9020"
  spanner-cli:
    image: sjdaws/spanner-cli:latest
    environment:
      SPANNER_EMULATOR_HOST: "spanner:9010"
    command:
      [
        'sh',
        '-c',
        'echo this container keep running && tail -f /dev/null'
      ]
