apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: locust-master
  name: locust-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locust-master
  template:
    metadata:
      labels:
        app: locust-master
    spec:
      containers:
        - env:
          image: gcr.io/kazu0716-sandbox/locust:e12b944
          command: ["/usr/local/bin/locust"]
          args: ["-f", "/user/src/app/locustfile.py", "--master"]
          imagePullPolicy: IfNotPresent
          name: locust-master
          ports:
            - name: loc-master-web
              containerPort: 8089
              protocol: TCP
            - name: loc-master-p1
              containerPort: 5557
              protocol: TCP
            - name: loc-master-p2
              containerPort: 5558
              protocol: TCP
      nodeSelector:
        cloud.google.com/gke-nodepool: master-pool
