apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: locust-worker
  name: locust-worker
spec:
  replicas: 8
  selector:
    matchLabels:
      app: locust-worker
  template:
    metadata:
      labels:
        app: locust-worker
    spec:
      containers:
      - env:
        image: gcr.io/kazu0716-sandbox/locust:e12b944
        command: ["/usr/local/bin/locust"]
        args: ["-f", "/user/src/app/locustfile.py", "--worker", "--master-host", "locust-master"]
        imagePullPolicy: IfNotPresent
        name: locust-worker